### ISSUE TITLE
s3 upload not working on windows nodes

### ISSUE THREAD

**Issue by irrationalism** [jenkinsci/jobcacher-plugin#240]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.426.1
OS: Linux - 4.14.304-226.531.amzn2.x86_64
Java: 11.0.21 - Amazon.com Inc. (OpenJDK 64-Bit Server VM)
---
amazon-ecr:1.114.vfd22430621f5
analysis-model-api:11.13.0
ant:497.v94e7d9fffa_b_9
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
authentication-tokens:1.53.v1c90fd9191a_b_
aws-credentials:218.v1b_e9466ec5da_
aws-java-sdk:1.12.586-413.v6a_6c3a_420126
aws-java-sdk-cloudformation:1.12.586-413.v6a_6c3a_420126
aws-java-sdk-codebuild:1.12.586-413.v6a_6c3a_420126
aws-java-sdk-ec2:1.12.586-413.v6a_6c3a_420126
aws-java-sdk-ecr:1.12.586-413.v6a_6c3a_420126
aws-java-sdk-ecs:1.12.586-413.v6a_6c3a_420126
aws-java-sdk-efs:1.12.586-413.v6a_6c3a_420126
aws-java-sdk-elasticbeanstalk:1.12.586-413.v6a_6c3a_420126
aws-java-sdk-iam:1.12.586-413.v6a_6c3a_420126
aws-java-sdk-kinesis:1.12.586-413.v6a_6c3a_420126
aws-java-sdk-logs:1.12.586-413.v6a_6c3a_420126
aws-java-sdk-minimal:1.12.586-413.v6a_6c3a_420126
aws-java-sdk-secretsmanager:1.12.586-413.v6a_6c3a_420126
aws-java-sdk-sns:1.12.586-413.v6a_6c3a_420126
aws-java-sdk-sqs:1.12.586-413.v6a_6c3a_420126
aws-java-sdk-ssm:1.12.586-413.v6a_6c3a_420126
basic-branch-build-strategies:81.v05e333931c7d
blueocean:1.27.9
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.27.9
blueocean-commons:1.27.9
blueocean-config:1.27.9
blueocean-core-js:1.27.9
blueocean-dashboard:1.27.9
blueocean-display-url:2.4.2
blueocean-events:1.27.9
blueocean-git-pipeline:1.27.9
blueocean-github-pipeline:1.27.9
blueocean-i18n:1.27.9
blueocean-jira:1.27.9
blueocean-jwt:1.27.9
blueocean-personalization:1.27.9
blueocean-pipeline-api-impl:1.27.9
blueocean-pipeline-editor:1.27.9
blueocean-pipeline-scm-api:1.27.9
blueocean-rest:1.27.9
blueocean-rest-impl:1.27.9
blueocean-web:1.27.9
bootstrap5-api:5.3.2-2
bouncycastle-api:2.29
branch-api:2.1135.v8de8e7899051
build-failure-analyzer:2.4.2
build-history-manager:1.7.1
build-timestamp:1.0.3
build-user-vars-plugin:1.9
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.0.2
cloudbees-bitbucket-branch-source:856.v04c46c86f911
cloudbees-folder:6.858.v898218f3609d
cloudbees-jenkins-advisor:358.v58972d19b_1f0
code-coverage-api:4.99.0
command-launcher:107.v773860566e2e
commons-httpclient3-api:3.1-3
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.11.0-94.v3e1f4a_926e49
conditional-buildstep:1.4.3
coverage:1.6.0
credentials:1309.v8835d63eb_d8a_
credentials-binding:642.v737c34dea_6c2
crowd2:4.2.0
data-tables-api:1.13.8-1
display-url-api:2.200.vb_9327d658781
docker-commons:439.va_3cb_0a_6a_fb_29
docker-workflow:572.v950f58993843
dtkit-api:3.0.2
durable-task:523.va_a_22cf15d5e0
ec2:1648.vf3d852e00486
echarts-api:5.4.3-1
external-monitor-job:215.v2e88e894db_f8
favorite:2.4.3
font-awesome-api:6.5.1-1
forensics-api:2.3.0
git:5.2.1
git-client:4.6.0
git-forensics:2.0.0
git-server:99.va_0826a_b_cdfa_d
github:1.37.3.1
github-api:1.318-461.v7a_c09c9fa_d63
github-branch-source:1752.vc201a_0235d80
groovy:457.v99900cb_85593
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
htmlpublisher:1.32
http_request:1.18
influxdb:3.5
instance-identity:185.v303dc7c645f9
ionicons-api:56.v1b_1c8c49374e
jackson2-api:2.15.3-372.v309620682326
jacoco:3.3.5
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javadoc:243.vb_b_503b_b_45537
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.9-1
jdk-tool:73.vddf737284550
jenkins-design-language:1.27.9
jersey2-api:2.41-133.va_03323b_a_1396
jira:3.12
jjwt-api:0.11.5-77.v646c772fddb_0
jnr-posix-api:3.1.18-1
job-dsl:1.87
jobcacher:409.vc3fde9f9b_f30
jquery3-api:3.7.1-1
jsch:0.2.8-65.v052c39de79b_2
junit:1240.vf9529b_881428
kubernetes-cli:1.12.1
kubernetes-client-api:6.8.1-224.vd388fca_4db_3b_
kubernetes-credentials:0.11
ldap:711.vb_d1a_491714dc
locale:314.v22ce953dfe9e
lockable-resources:1215.v895f61d7f794
mailer:463.vedf8358e006b_
matrix-auth:3.2.1
matrix-project:818.v7eb_e657db_924
maven-plugin:3.23
mercurial:1260.vdfb_723cdcc81
metrics:4.2.18-442.v02e107157925
mina-sshd-api-common:2.11.0-86.v836f585d47fa_
mina-sshd-api-core:2.11.0-86.v836f585d47fa_
monitoring:1.95.0
mstest:1.0.5
nexus-artifact-uploader:2.14
nexus-jenkins-plugin:3.16.510.v4d23e22cf563
node-iterator-api:55.v3b_77d4032326
okhttp-api:4.11.0-157.v6852a_a_fa_ec11
pam-auth:1.10
parameterized-scheduler:255.v73827fcdf618
performance:951.v5600a_c6422ed
periodicbackup:2.0
pipeline-aws:1.43
pipeline-build-step:516.v8ee60a_81c5b_9
pipeline-github-lib:42.v0739460cda_c4
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-groovy-lib:689.veec561a_dee13
pipeline-input-step:477.v339683a_8d55e
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2151.ve32c9d209a_3f
pipeline-model-definition:2.2151.ve32c9d209a_3f
pipeline-model-extensions:2.2151.ve32c9d209a_3f
pipeline-rest-api:2.34
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2151.ve32c9d209a_3f
pipeline-stage-view:2.34
pipeline-utility-steps:2.16.0
plain-credentials:143.v1b_df8b_d3b_e48
plugin-usage-plugin:4.2
plugin-util-api:3.6.0
prism-api:1.29.0-9
pubsub-light:1.18
resource-disposer:0.23
role-strategy:689.v731678c3e0eb_
run-condition:1.7
scm-api:683.vb_16722fb_b_80b_
script-security:1294.v99333c047434
slack:684.v833089650554
snakeyaml-api:2.2-111.vc6598e30cc65
sonar:2.16.1
sse-gateway:1.26
ssh-agent:346.vda_a_c4f2c8e50
ssh-credentials:308.ve4497b_ccd8f4
ssh-slaves:2.916.vd17b_43357ce4
sshd:3.312.v1c601b_c83b_0e
strict-crumb-issuer:2.1.1
structs:325.vcb_307d2a_2782
support-core:1366.v9d076592655d
timestamper:1.26
token-macro:384.vf35b_f26814ec
trilead-api:2.84.v72119de229b_7
variant:60.v7290fc0eb_b_cd
warnings-ng:10.5.2
windows-slaves:1.8.1
workflow-aggregator:596.v8c21c963d92d
workflow-api:1283.v99c10937efcb_
workflow-basic-steps:1042.ve7b_140c4a_e0c
workflow-cps:3812.vc3031a_b_a_c955
workflow-cps-global-lib:609.vd95673f149b_b
workflow-durable-task-step:1289.v4d3e7b_01546b_
workflow-job:1360.vc6700e3136f5
workflow-multibranch:756.v891d88f2cd46
workflow-scm-step:415.v434365564324
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:865.v43e78cc44e0d
ws-cleanup:0.45
xunit:3.1.3

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Controller is Linux.
Worker is Windows Server 2022.

### Reproduction steps

```
cache(maxCacheSize: 512, caches: [
    [$class                   : 'ArbitraryFileCache',
     path                     : 'Global',
     compressionMethod        : 'TARGZ',
    ]
],
) {
  sh(script: 'ls -la . || true',
      label: 'test2',
  )
}

```

### Expected Results

Cache (few KB) gets uploaded to AWS S3.

### Actual Results

Timeout is triggered after approx. 5min.
```
17:42:10  [Cache for Global with id 4cc6684df7b4a92b1dec6fce3264fac8] Searching cache in job specific caches...
17:42:10  [Cache for Global with id 4cc6684df7b4a92b1dec6fce3264fac8] Searching cache in default caches...
17:42:10  [Cache for Global with id 4cc6684df7b4a92b1dec6fce3264fac8] Skip restoring cache as no up-to-date cache exists
...
17:48:16  drwxr-xr-x 1 Administrator 197121     0 Dec  4 17:46 Global
17:48:16  -rw-r--r-- 1 Administrator 197121  1033 Dec  4 17:46 Jenkinsfile
...
17:48:32  [Cache for Global with id 4cc6684df7b4a92b1dec6fce3264fac8] Creating cache...
17:53:18  [Cache for Global with id 4cc6684df7b4a92b1dec6fce3264fac8] Failed to create cache
17:53:18  java.lang.InterruptedException
17:53:18  	at java.base/java.lang.Object.wait(Native Method)
17:53:18  	at hudson.remoting.Request.call(Request.java:177)
17:53:18  	at hudson.remoting.Channel.call(Channel.java:1002)
17:53:18  	at hudson.FilePath.act(FilePath.java:1192)
17:53:18  	at hudson.FilePath.act(FilePath.java:1181)
17:53:18  	at jenkins.plugins.itemstorage.s3.S3Profile.upload(S3Profile.java:69)
17:53:18  	at jenkins.plugins.itemstorage.s3.S3ObjectPath.copyFrom(S3ObjectPath.java:75)
17:53:18  	at jenkins.plugins.jobcacher.arbitrary.AbstractCompressingArbitraryFileCacheStrategy.cache(AbstractCompressingArbitraryFileCacheStrategy.java:20)
17:53:18  	at jenkins.plugins.jobcacher.ArbitraryFileCache$SaverImpl.save(ArbitraryFileCache.java:383)
17:53:18  	at jenkins.plugins.jobcacher.CacheManager.save(CacheManager.java:96)
17:53:18  	at jenkins.plugins.jobcacher.pipeline.CacheStepExecution$ExecutionCallback.complete(CacheStepExecution.java:101)
17:53:18  	at jenkins.plugins.jobcacher.pipeline.CacheStepExecution$ExecutionCallback.onSuccess(CacheStepExecution.java:78)
17:53:18  	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$SuccessAdapter.receive(CpsBodyExecution.java:375)
17:53:18  	at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBlock.java:39)
17:53:18  	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
17:53:18  	at com.cloudbees.groovy.cps.impl.LocalVariableBlock.evalLValue(LocalVariableBlock.java:28)
17:53:18  	at com.cloudbees.groovy.cps.LValueBlock$BlockImpl.eval(LValueBlock.java:55)
17:53:18  	at com.cloudbees.groovy.cps.LValueBlock.eval(LValueBlock.java:16)
17:53:18  	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
17:53:18  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:152)
17:53:18  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:146)
17:53:18  	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
17:53:18  	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
17:53:18  	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:146)
17:53:18  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
17:53:18  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
17:53:18  	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:187)
17:53:18  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:423)
17:53:18  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:331)
17:53:18  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:295)
17:53:18  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:97)
17:53:18  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
17:53:18  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
17:53:18  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
17:53:18  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
17:53:18  	at jenkins.util.ErrorLoggingExecutorService.lambda$wrap$0(ErrorLoggingExecutorService.java:51)
17:53:18  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
17:53:18  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
17:53:18  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
17:53:18  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
17:53:18  	at java.base/java.lang.Thread.run(Thread.java:829)
...



```

### Anything else?

Cache upload is working on linux nodes without problems

**Comment by jonesbusy** [comment]
Looking at the timestamp is was due to the 5mn CPS timeout

Should be fixed by https://github.com/jenkinsci/jobcacher-plugin/pull/396

Feel free to reopen
