### ISSUE TITLE
Support absence of file configured in cacheValidityDecidingFile

### ISSUE THREAD

**Issue by darxriggs** [jenkinsci/jobcacher-plugin#93]
### What feature do you want to see added?

**Expected behaviour**
When a `cacheValidityDecidingFile` is configured but the file does not exist (yet), no error is raised and no cache restore is performed.

**Current behaviour**
When the file does not exist, the error is as follows:
```
FATAL: path validity-file cannot be resolved within the current workspace
java.lang.IllegalStateException: path validity-file cannot be resolved within the current workspace
	at jenkins.plugins.jobcacher.ArbitraryFileCache.getCurrentCacheValidityDecidingFileHash(ArbitraryFileCache.java:236)
	at jenkins.plugins.jobcacher.ArbitraryFileCache.matchesCurrentCacheValidityDecidingFileHash(ArbitraryFileCache.java:229)
	at jenkins.plugins.jobcacher.ArbitraryFileCache.isCacheOutdated(ArbitraryFileCache.java:209)
	at jenkins.plugins.jobcacher.ArbitraryFileCache.resolveValidCache(ArbitraryFileCache.java:188)
	at jenkins.plugins.jobcacher.ArbitraryFileCache.resolveValidCache(ArbitraryFileCache.java:167)
	at jenkins.plugins.jobcacher.ArbitraryFileCache.cache(ArbitraryFileCache.java:148)
	at jenkins.plugins.jobcacher.CacheManager.cache(CacheManager.java:64)
	at jenkins.plugins.jobcacher.CacheWrapper.setUp(CacheWrapper.java:104)
	at jenkins.tasks.SimpleBuildWrapper.setUp(SimpleBuildWrapper.java:294)
	at hudson.model.Build$BuildExecution.doRun(Build.java:157)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:514)
	at hudson.model.Run.execute(Run.java:1888)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:99)
	at hudson.model.Executor.run(Executor.java:431)
```

The `config.xml` of a simple job to reproduce this:
```
<?xml version='1.1' encoding='UTF-8'?>
<project>
  <actions/>
  <description></description>
  <keepDependencies>false</keepDependencies>
  <properties/>
  <scm class="hudson.scm.NullSCM"/>
  <canRoam>true</canRoam>
  <disabled>false</disabled>
  <blockBuildWhenDownstreamBuilding>false</blockBuildWhenDownstreamBuilding>
  <blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>
  <triggers/>
  <concurrentBuild>false</concurrentBuild>
  <builders>
    <hudson.tasks.Shell>
      <command>
echo test &gt; validity-file
echo foo &gt; data-file
      </command>
      <configuredLocalRules/>
    </hudson.tasks.Shell>
  </builders>
  <publishers/>
  <buildWrappers>
    <jenkins.plugins.jobcacher.CacheWrapper plugin="jobcacher@999999-SNAPSHOT">
      <maxCacheSize>32</maxCacheSize>
      <caches>
        <jenkins.plugins.jobcacher.ArbitraryFileCache>
          <path>.</path>
          <includes>**/*</includes>
          <excludes></excludes>
          <useDefaultExcludes>true</useDefaultExcludes>
          <cacheValidityDecidingFile>validity-file</cacheValidityDecidingFile>
          <compressionMethod>ZIP</compressionMethod>
        </jenkins.plugins.jobcacher.ArbitraryFileCache>
      </caches>
      <defaultBranch></defaultBranch>
    </jenkins.plugins.jobcacher.CacheWrapper>
  </buildWrappers>
</project>
```

The change could be to check for the existence of the file in [ArbitraryFileCache::matchesCurrentCacheValidityDecidingFileHash](https://github.com/jenkinsci/jobcacher-plugin/blob/281.v338c5559864d/src/main/java/jenkins/plugins/jobcacher/ArbitraryFileCache.java#L226-L231) before accessing it and to return `false` if it is absent.

**Comment by repolevedavaj** [comment]
@darxriggs I created a PR for this change. Feel free to check it out.
